# Generated by Django 3.2.5 on 2021-08-07 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WM',
            new_name='tahlee',
        ),
    ]
