# Generated by Django 3.2.5 on 2021-08-07 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_rename_wm_tahlee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tahlee',
            new_name='Ultahlee',
        ),
    ]
