# Generated by Django 3.2.5 on 2021-08-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0003_rename_tahlee_ultahlee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ultahlee',
            new_name='NewModel',
        ),
    ]
